cache:
    directories:
        - $HOME/.composer/cache

services:
    - docker

before_install:
    - envsubst < docker-compose.override.travis.yml > docker-compose.override.yml
    - docker network create nginx-proxy
    - curl -LO https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - curl -LO https://github.com/phpstan/phpstan-shim/raw/0.8/phpstan.phar

install:
    - docker-compose up -d web
    - docker-compose run composer

script:
    - docker-compose exec -T web php phpstan.phar analyse -l 7 app tests
    - docker-compose exec -T web vendor/bin/phpunit tests --coverage-clover log/coverage.xml --whitelist app

after_script:
    - docker-compose exec web php coveralls.phar -v
