version: '3'

services:
  web:
    volumes:
     - ./docker/web/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      DEBUG_MODE: 1
      TRAVIS: "$TRAVIS"
      TRAVIS_JOB_ID: "$TRAVIS_JOB_ID"
