version: '3'

services:
  nginx:
    environment:
      VIRTUAL_HOST: vitkutny.cz.test

  web:
    volumes:
     - ./docker/web/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
      DEBUG_MODE: 1

networks:
  default:
    external:
      name: nginx-proxy
