version: '3'

services:
    nginx:
        image: nginx:alpine
        ports:
          - 80
        volumes:
          - ./:/var/www/html
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
          - web
        restart: on-failure

    web:
        image: vitkutny/docker:vitkutny.cz_web
        volumes:
          - ./:/var/www/html
        expose:
          - 9000
        restart: on-failure

    composer:
        image: vitkutny/docker:vitkutny.cz_web
        entrypoint: composer
        command: install
        volumes:
          - ./:/var/www/html

    webpack:
        image: node:alpine
        command: sh -cl "yarn install --ignore-engines && yarn run webpack --production"
        volumes:
          - ./:/app
        working_dir: /app
