version: '3'

services:
  nginx:
    environment:
      VIRTUAL_HOST: vitkutny.local

  php-fpm:
    volumes:
     - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
      DEBUG_MODE: 1@172.17.0.2

  composer:
    command: install --ignore-platform-reqs

networks:
  default:
    external:
      name: nginx-proxy
